version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 7777:8080
